title: "Ilina Yozova"
email: ilina.yozova.18@ucl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://ilinayozova.github.io/" 
twitter_username: IYozova
github_username:  ilinayozova

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
